[package]
name = "lowc"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
analysis = { path = "../analysis" }
assemble = { path = "../assemble" }
target-lexicon = "0.11.0"
