[package]
name = "lowlang"
version = "0.1.0"
authors = ["Cyberduc-k <cyberduck_@outlook.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "diagnostics" }
syntax = { path = "syntax" }
check = { path = "check" }
vm = { path = "vm" }
backend-cranelift = { path = "backend-cranelift" }