[package]
name = "lowlang"
version = "0.1.0"
authors = ["Cyberduc-k <cyberduck_@outlook.com>"]
edition = "2018"

[dependencies]
intern = { path = "intern" }
diagnostics = { path = "diagnostics" }
syntax = { path = "syntax" }
