[package]
name = "ll-cranelift"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
syntax = { path = "../syntax" }
cranelift-simplejit = "*"
cranelift-module = "*"
cranelift = "*"