[package]
name = "codegen_cranelift"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
codegen = { path = "../codegen" }
cranelift = "0.68.0"
cranelift-module = "0.68.0"
cranelift-object = "0.68.0"
target-lexicon = "0.11.0"
