[package]
name = "backend-clif"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
ir = { path = "../ir" }
arena = { git = "https://github.com/Xiulf/arena.git" }
target-lexicon = "0.12.0"
tempfile = "3.2.0"
