[package]
name = "codegen"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
eval = { path = "../eval" }
target-lexicon = "0.11.0"
tempfile = "3.1.0"
