[package]
name = "codegen"
version = "0.1.0"
edition = "2018"

[dependencies]
ir = { path = "../ir" }
arena = { git = "https://github.com/Xiulf/arena.git" }
tempfile = "3.2.0"

[dependencies.inkwell]
git = "https://github.com/TheDan64/inkwell"
branch = "master"
features = ["llvm11-0"]
