[package]
name = "lowlang-syntax"
version = "0.1.0"
authors = ["Cyberduc-k <cyberduck_@outlook.com>"]
edition = "2018"

[dependencies]
lowlang-parser = { path = "../lowlang-parser" }
intern = { path = "../../fluix/intern" }
lazy_static = "1.4.0"
target-lexicon = "0.10.0"
