[package]
name = "syntax"
version = "0.1.0"
authors = ["Cyberduc-k <cyberduck_@outlook.com>"]
edition = "2018"

[dependencies]
parser = { path = "../parser" }
intern = { path = "../intern" }
lazy_static = "1.4.0"
target-lexicon = "0.10.0"
