[package]
name = "syntax"
version = "0.1.0"
authors = ["Cyberduc-k <cyberduck_@outlook.com>"]
edition = "2018"

[dependencies]
parser = { path = "parser" }
fluix-encode = { git = "https://github.com/Cyberduc-k/fluix.git", branch = "yet-another-rewrite" }