[package]
name = "lowlang-check"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
diagnostics = { path = "../../.crates/diagnostics" }
intern = { path = "../../.crates/intern" }
lowlang-syntax = { path = "../lowlang-syntax" }
