[package]
name = "intern"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
parking_lot = { version = "0.10.0", features = ["nightly"] }
