[package]
name = "analysis"
version = "0.1.0"
authors = ["Cyberduc-k <tttymo@gmail.com>"]
edition = "2018"

[dependencies]
ir = { path = "../ir" }
transform = { path = "../transform" }
indexmap = "1.6.0"
